name: "test"
n_gpu: 1

img_size: 256

checkpoint: path/to/checkpoint.pth

StarGANv2:
  _target_: src.model.model.StarGANv2
  generator_config:
    initial_dim: 64
    img_size: 256
    style_dim: 64
    max_conv_dim: 512
  mapping_network_config:
    latent_dim: 16
    style_dim: 64
    hidden_dim: 512
    num_domains: 10
  style_encoder_config:
    initial_dim: 64
    img_size: 256
    style_dim: 64
    num_domains: 10
    max_conv_dim: 512
  discriminator_config:
    initial_dim: 64
    img_size: 256
    num_domains: 10
    max_conv_dim: 512

metrics:
  - _target_: src.metric.LPIPS_Wrapper
    name: LPIPS_Wrapper